name: ItemSorters
version: '${project.version}'
main: com.somemone.itemsorters.ItemSorters
api-version: 1.17
description: Sorts items, but with GUIS!

commands:
  sorter:
    usage: /sorter <create|add|remove|invite|kick|leave|view>
    description: Create and manage sorters

permissions:
  sorter.create:
    default: op
  sorter.add:
    default: op
  sorter.view:
    default: true
  sorter.invite:
    default: op
  sorter.join:
    default: true
